repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
- repo: https://github.com/igorshubovych/markdownlint-cli2
  rev: v0.13.0
  hooks:
    - id: markdownlint-cli2
      name: markdownlint-readmes
      args: ["--fix", "**/README.md"]
      pass_filenames: false
      always_run: true
